### ISSUE TITLE
A constructor operation isn't linked like the extended attribute is

### ISSUE THREAD

**Issue by foolip** [tabatkins/bikeshed#1519]
See https://github.com/whatwg/dom/pull/782#issuecomment-529151359.

I haven't looked into what the problem is, but presumably Bikeshed needs some changes.

@Ms2ger is this something you've run into already?

**Comment by tabatkins** [comment]
Yes, Bikeshed needs changes here, haven't gotten to it yet. Thanks for the bug to track it.

**Comment by foolip** [comment]
Thanks for confirming, Tab!

@Ms2ger FYI I think this should block sending lots of PRs for Bikeshed specs, as probably lots of specs would have links broken without the maintainers noticing.

**Comment by tabatkins** [comment]
Eh, they'll fix on next build, it'll be fine.  I'll fix this either Monday or Tuesday.

**Comment by birtles** [comment]
Also, it appears the IDs generated for parameters to constructor operations are not correctly scoped to the constructor operation (and hence can overlap with interface members of the same name).

**Comment by tabatkins** [comment]
Okay, "constructor" should be linking/dfning properly now. You can autolink to it either as "constructor()" or as "InterfaceName()".

The args problem is due to a bug in widlparser, which plinss is looking into right now.

**Comment by tabatkins** [comment]
And arguments should be working now.

**Comment by birtles** [comment]
I still can't get this to work with the latest bikeshed. The argument linking works but it doesn't link the constructor definition given the following markup:

```
<pre class="idl">
dictionary DocumentTimelineOptions {
  DOMHighResTimeStamp originTime = 0;
};

[Exposed=Window]
interface DocumentTimeline : AnimationTimeline {
  constructor(optional DocumentTimelineOptions options = {});
};
</pre>

<div class=constructors>

:   <dfn constructor for=DocumentTimeline
    lt="constructor(options)">constructor (options)</dfn>
::  Creates a new {{DocumentTimeline}}.

</div>
```

I've tried `DocumentTimeline()`, `DocumentTimeline(options)`, `constructor()`, and `constructor(options)` as the link text but none of them appear to work.

**Comment by tabatkins** [comment]
Ah! Sorry, that's because `constructor()` is currently getting marked up as a "method" type.

I'll switch it back to "constructor".

**Comment by birtles** [comment]
Thank you!

**Comment by tabatkins** [comment]
Done in 7b13078e

**Comment by birtles** [comment]
Works a treat. Thank you!
