### ISSUE TITLE
force=Document does not work in DOM

### ISSUE THREAD

**Issue by annevk** [tabatkins/bikeshed#403]
And addEventListener() currently links to HTML rather than the definition inside DOM. Not sure if there are more such links.

**Comment by tabatkins** [comment]
Hrm. I'll look into this shortly.

**Comment by tabatkins** [comment]
Fixed. (That was a long "shortly"!)

**Comment by annevk** [comment]
This is not fixed still. E.g. `interface Document` links to HTML.

**Comment by tabatkins** [comment]
??? No it doesn't.  Both on my fork of your repo, and *on the live document on whatwg.org*, the "Document" in `interface Document {` is dfn'd, not linked.
